### ISSUE TITLE
Incorrect data limit

### ISSUE THREAD

**Issue by benesjan** [ArweaveTeam/arweave-deploy#12]
Hello, it seems that the data limit is much lower than the 10 MB. I tried to upload ~2 MB video to the network with command:
`
honza@honza-MS-7823:~$ arweave deploy '/home/honza/Coding/video-presence-tracker/video_out/output.mp4' --key-file '/home/honza/Downloads/arweave-keyfile-325zf8JIBC96nPoINPMbu8IJk-_vVC2ZNT2lIRpoNFs.json'`

and got the following output:
`
Detected byte size: 2.13 MB
Data uploads are currently limited to 10MB per transaction.
`

**Comment by aidanok** [comment]
Hey @benesjan , This is a bug in the released version of the the arweave-deploy tool. There is a partial fix already in master that increases the limit to 7MB, you can as a workaround build a local copy to use: 

```
git clone https://github.com/ArweaveTeam/arweave-deploy.git
cd arweave-deploy 
npm i 
npm run build 
```
This will produce `dist/arweave` which allows 7MiB uploads for the deploy command. 

The fix for the full 10MiB will be released and published on npm asap. 

Thanks !
